### PR TITLE
Add support for pry 0.11.x

### PR DESCRIPTION
**Pull request by rrosenblum**

### CODE REVIEW

**Comment by seikichi** [comment]
@rrosenblum Thanks! (thanks for updating `.travis.yml` !!)

**Comment by seikichi** [comment]
I'll release the new version today, please wait ;-p

**Comment by seikichi** [comment]
https://rubygems.org/gems/pry-inline/versions/1.0.4

**Comment by rrosenblum** [comment]
Thank you.

**Pull request merged**
